DROP DATABASE IF EXISTS locadora;

CREATE DATABASE locadora;

USE locadora;

CREATE TABLE cliente (
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nome VARCHAR(45) NOT NULL,
	telefone VARCHAR(45) NOT NULL,
	email VARCHAR(45) NOT NULL,
	sexo VARCHAR(45) NOT NULL,
	idade INTEGER NOT NULL
);

CREATE TABLE filme (
	id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
	titulo VARCHAR(45) NOT NULL,
	genero VARCHAR(45) NOT NULL,
	duracao INTEGER NOT NULL,
	price DOUBLE NOT NULL
);